# Generated by Django 6.0.3 on 2026-03-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_course_duration_hours_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learning_outcomes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='module',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
