# Generated by Django 6.0.3 on 2026-03-21 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_course_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('lesson_type', models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('image', 'Image'), ('quiz', 'Quiz'), ('pdf', 'PDF'), ('assignment', 'Assignment')], default='text', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=0)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='hub.module')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
