# Generated by Django 6.0.3 on 2026-03-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_add_lesson_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='quiz_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
