# Generated by Django 6.0.3 on 2026-05-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_course_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='competency_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='goals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subject_area',
            field=models.CharField(blank=True, choices=[('stem', 'STEM'), ('humanities', 'Humanities'), ('languages', 'Languages'), ('arts', 'Arts'), ('general', 'General / Multiple')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='teaching_level',
            field=models.CharField(blank=True, choices=[('primary', 'Primary (K-6)'), ('secondary', 'Secondary (7-12)'), ('higher_ed', 'Higher Education'), ('vocational', 'Vocational'), ('adult_ed', 'Adult Education')], max_length=20),
        ),
    ]
