# Generated by Django 6.0.3 on 2026-05-15 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0012_add_recommendation_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_completed', models.FloatField(default=1.0)),
                ('w_deep', models.FloatField(default=0.7)),
                ('w_active', models.FloatField(default=0.4)),
                ('w_enrolled', models.FloatField(default=0.2)),
                ('w_abandoned', models.FloatField(default=-0.1)),
                ('w_lesson', models.FloatField(default=0.03)),
                ('w_view', models.FloatField(default=0.1)),
                ('alpha', models.FloatField(default=0.3)),
                ('beta', models.FloatField(default=0.5)),
                ('gamma', models.FloatField(default=0.2)),
                ('style_boost', models.FloatField(default=1.2)),
                ('bandit_active', models.BooleanField(default=False)),
                ('n_min', models.IntegerField(default=200)),
                ('n_full', models.IntegerField(default=1000)),
                ('learning_rate', models.FloatField(default=0.01)),
                ('reward_click', models.FloatField(default=0.3)),
                ('reward_enroll', models.FloatField(default=0.5)),
                ('reward_complete', models.FloatField(default=1.0)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='content_format',
            field=models.CharField(choices=[('video', 'Video'), ('text', 'Text'), ('visual', 'Visual'), ('interactive', 'Interactive'), ('mixed', 'Mixed')], default='mixed', max_length=20),
        ),
        migrations.AddField(
            model_name='courserecommendation',
            name='source',
            field=models.CharField(default='personal', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='learning_style',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('text', 'Text'), ('visual', 'Visual'), ('interactive', 'Interactive')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_pillars',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='CourseView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_views', to='hub.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('shown', 'Shown'), ('clicked', 'Clicked'), ('enrolled', 'Enrolled'), ('completed', 'Completed')], max_length=20)),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('source', models.CharField(max_length=20)),
                ('weights_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_events', to='hub.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
