# Generated by Django 6.0.3 on 2026-06-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0014_enrollment_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='engagement_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='quiz_answers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='quiz_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='time_spent_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
