# Generated by Django 6.0.3 on 2026-07-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0019_userprofile_gender_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
