# Generated by Django 6.0.3 on 2026-07-18 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0020_userprofile_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PreferenceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('maps_to', models.CharField(choices=[('video', 'Video'), ('text', 'Text'), ('visual', 'Visual'), ('interactive', 'Interactive')], max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='hub.preferencequestion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
