# Generated by Django 6.0.3 on 2026-07-19 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0021_preference_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='decay_applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learneractivityconfig',
            name='decay_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='learneractivityconfig',
            name='idle_decay_days',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='learneractivityconfig',
            name='idle_decay_points',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='learneractivityconfig',
            name='slow_penalty',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='learneractivityconfig',
            name='slow_ratio_threshold',
            field=models.FloatField(default=3.0),
        ),
    ]
