# Generated by Django 6.0.3 on 2026-07-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0023_assignment_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('el', 'Ελληνικά'), ('fr', 'Français'), ('es', 'Español'), ('it', 'Italiano'), ('fi', 'Suomi'), ('sv', 'Svenska'), ('no', 'Norsk'), ('de', 'Deutsch')], default='en', max_length=5),
        ),
    ]
