# Generated by Django 6.0.3 on 2026-07-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0024_profile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='source_language',
            field=models.CharField(default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='course',
            name='translation_status',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='course',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lesson',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='module',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
