# Generated by Django 6.0.3 on 2026-07-23 15:42

import django.db.models.deletion
from django.db import migrations, models

# The shared subject taxonomy (name, slug, order).
SUBJECTS = [
    ('Mathematics', 'mathematics'),
    ('Physics', 'physics'),
    ('Chemistry', 'chemistry'),
    ('Biology', 'biology'),
    ('Astronomy', 'astronomy'),
    ('Computer Science', 'computer-science'),
    ('Engineering & Technology', 'engineering-technology'),
    ('Geography', 'geography'),
    ('History', 'history'),
    ('Social Studies', 'social-studies'),
    ('Economics & Business', 'economics-business'),
    ('Languages', 'languages'),
    ('Literature & English', 'literature-english'),
    ('Arts', 'arts'),
    ('Music', 'music'),
    ('Physical Education', 'physical-education'),
    ('General / All', 'general'),
]

# Best-effort mapping from the old broad subject_area values to a new subject.
# The umbrella categories (STEM / Humanities / General) collapse to General/All.
OLD_TO_NEW_SLUG = {
    'languages': 'languages',
    'arts': 'arts',
    'stem': 'general',
    'humanities': 'general',
    'general': 'general',
}


def seed_and_migrate(apps, schema_editor):
    Subject = apps.get_model('hub', 'Subject')
    UserProfile = apps.get_model('hub', 'UserProfile')

    by_slug = {}
    for order, (name, slug) in enumerate(SUBJECTS, start=1):
        obj, _ = Subject.objects.get_or_create(
            slug=slug, defaults={'name': name, 'order': order},
        )
        by_slug[slug] = obj

    for profile in UserProfile.objects.exclude(subject_area=''):
        new_slug = OLD_TO_NEW_SLUG.get(profile.subject_area)
        if new_slug and new_slug in by_slug:
            profile.subject = by_slug[new_slug]
            profile.save(update_fields=['subject'])


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0025_content_translations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='courses', to='hub.subject'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='hub.subject'),
        ),
        # Seed subjects and migrate old values BEFORE dropping the old column.
        migrations.RunPython(seed_and_migrate, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='userprofile',
            name='subject_area',
        ),
    ]
