# Generated by Django 6.0.3 on 2026-07-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0028_seed_onboarding_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlearningpath',
            name='course_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
