# Generated by Django 6.0.3 on 2026-07-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0029_userlearningpath_course_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='media_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
