# Generated by Django 6.0.3 on 2026-07-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0031_migrate_media_to_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
