# Generated by Django 6.0.3 on 2026-07-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0032_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
