# Generated by Django 6.0.3 on 2026-07-27 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0034_conversation_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(choices=[('user', 'User feedback'), ('partner', 'Partner feedback')], default='user', max_length=10)),
                ('category', models.CharField(choices=[('bug', 'Bug'), ('suggestion', 'Suggestion'), ('feedback', 'Feedback'), ('feature_request', 'Feature request'), ('content_issue', 'Content issue')], max_length=20)),
                ('message', models.TextField()),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Under review'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='new', max_length=15)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_feedback', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
