# Generated by Django 6.0.3 on 2026-07-27 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0035_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyAssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudyAssessmentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='hub.studyassessmentquestion')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('post_test_open', models.BooleanField(default=False, help_text='When on, participants who finished the pre-test can take the post-test.')),
                ('control_path', models.ForeignKey(blank=True, help_text='Fixed course sequence given to the control (fixed) group.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hub.learningpath')),
            ],
            options={
                'verbose_name': 'Study configuration',
            },
        ),
        migrations.CreateModel(
            name='StudyParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_study', models.BooleanField(default=False)),
                ('group', models.CharField(blank=True, choices=[('adaptive', 'Adaptive'), ('fixed', 'Fixed')], max_length=10)),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('pre_score', models.IntegerField(blank=True, null=True)),
                ('pre_completed_at', models.DateTimeField(blank=True, null=True)),
                ('post_score', models.IntegerField(blank=True, null=True)),
                ('post_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
