# Generated by Django 6.0.3 on 2026-07-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0036_studyassessmentquestion_studyassessmentoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accepted_terms_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
