# Generated by Django 6.0.3 on 2026-07-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0037_userprofile_accepted_terms_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingoption',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='onboardingquestion',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
