# Generated by Django 6.0.3 on 2026-07-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0038_onboardingoption_translations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_status', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
