# Generated by Django 6.0.3 on 2026-07-30 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0039_onboardingconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('translations', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='onboardingquestion',
            options={'ordering': ['dimension__order', 'order']},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='self_efficacy_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='self_efficacy_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingquestion',
            name='dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='hub.onboardingdimension'),
        ),
        migrations.DeleteModel(
            name='OnboardingOption',
        ),
    ]
