# Generated by Django 6.0.3 on 2026-07-30 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0041_seed_self_efficacy_questions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnboardingConfig',
        ),
    ]
