# Generated by Django 6.0.3 on 2026-07-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0043_selfefficacyconfig_selfefficacyattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfefficacyconfig',
            name='retake_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
