# Generated by Django 6.0.3 on 2026-07-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0044_selfefficacyconfig_retake_opened_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='self_efficacy_draft',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='self_efficacy_retaking',
            field=models.BooleanField(default=False),
        ),
    ]
