# Generated by Django 6.0.3 on 2026-08-21 08:42

from django.db import migrations, models


def grandfather_existing(apps, schema_editor):
    # Existing accounts predate verification — treat them as already verified so
    # they aren't nagged. New accounts default to False.
    apps.get_model('hub', 'UserProfile').objects.update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0046_seed_self_efficacy_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(grandfather_existing, migrations.RunPython.noop),
    ]
