# Generated by Django 6.0.3 on 2026-08-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0048_maintenancenotice'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPreregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hypothesis', models.TextField(blank=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Study pre-registration',
            },
        ),
    ]
