# Generated by Django 6.0.3 on 2026-09-29 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0050_coursecollaborator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('image', 'Image'), ('pdf', 'PDF'), ('quiz', 'Quiz'), ('assignment', 'Assignment')], max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('quiz_data', models.JSONField(blank=True, default=list)),
                ('instructions', models.TextField(blank=True)),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='hub.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
