# Generated by Django 6.0.3 on 2026-10-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0051_userprofile_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='additional_pillars',
            field=models.ManyToManyField(blank=True, related_name='secondary_courses', to='hub.learningpillar'),
        ),
        migrations.AddField(
            model_name='course',
            name='cross_axis_relevance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='educational_level_other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='educational_levels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='prior_knowledge',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='target_audience',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='target_audience_other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='module',
            name='related_outcomes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
