# Generated by Django 6.0.3 on 2026-10-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0052_course_proposal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='school_role',
            field=models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('school_leader', 'School leader'), ('both', 'Teacher and school leader')], max_length=20),
        ),
    ]
