# Generated by Django 6.0.3 on 2026-09-29 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0052_resourceprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='hub.resource'),
        ),
    ]
