# Generated by Django 6.0.3 on 2026-10-01 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0051_userprofile_website'),
        ('hub', '0057_course_proposal_fields'),
    ]

    operations = [
    ]
