# Generated by Django 6.0.3 on 2026-10-01 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0053_userprofile_school_role'),
        ('hub', '0057_merge_master'),
    ]

    operations = [
    ]
