# Generated by Django 6.0.3 on 2026-10-01 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0054_sync_feedback_stream_with_role'),
        ('hub', '0058_merge_school_role'),
    ]

    operations = [
    ]
