# Generated by Django 6.0.3 on 2026-10-01 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0055_admin_feedback_to_partner_stream'),
        ('hub', '0059_merge_feedback_stream'),
    ]

    operations = [
    ]
