# Generated by Django 6.0.3 on 2026-10-01 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0060_merge_admin_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learneractivityconfig',
            name='tracking_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ResourceVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_key', models.UUIDField()),
                ('page_key', models.UUIDField()),
                ('started_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('active_seconds', models.PositiveIntegerField(default=0)),
                ('visible_seconds', models.PositiveIntegerField(default=0)),
                ('completed_during', models.BooleanField(default=False)),
                ('language', models.CharField(blank=True, max_length=8)),
                ('device', models.CharField(blank=True, choices=[('desktop', 'Desktop'), ('tablet', 'Tablet'), ('mobile', 'Mobile')], max_length=10)),
                ('local_hour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tz_offset_minutes', models.SmallIntegerField(blank=True, null=True)),
                ('media_progress', models.JSONField(blank=True, default=dict)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hub.activity')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hub.course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hub.module')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='hub.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_visits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.UUIDField()),
                ('event_type', models.CharField(choices=[('video_play', 'Video play'), ('video_pause', 'Video pause'), ('video_seek', 'Video seek'), ('video_ended', 'Video ended'), ('pdf_open', 'PDF opened'), ('pdf_download', 'PDF downloaded'), ('image_open', 'Image opened'), ('quiz_answer', 'Quiz answer')], max_length=20)),
                ('occurred_at', models.DateTimeField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hub.course')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hub.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_events', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='hub.resourcevisit')),
            ],
            options={
                'ordering': ['occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='resourcevisit',
            index=models.Index(fields=['course', 'user'], name='hub_resourc_course__268c22_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcevisit',
            index=models.Index(fields=['resource', 'user'], name='hub_resourc_resourc_5b8d83_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcevisit',
            index=models.Index(fields=['user', 'last_seen_at'], name='hub_resourc_user_id_a57dde_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcevisit',
            unique_together={('user', 'visit_key')},
        ),
        migrations.AddIndex(
            model_name='learningevent',
            index=models.Index(fields=['course', 'user'], name='hub_learnin_course__0fa764_idx'),
        ),
        migrations.AddIndex(
            model_name='learningevent',
            index=models.Index(fields=['resource', 'event_type'], name='hub_learnin_resourc_208ff9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='learningevent',
            unique_together={('user', 'event_key')},
        ),
    ]
