# Generated by Django 6.0.3 on 2026-10-08 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0061_learning_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='h5p_self_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='learningevent',
            name='event_type',
            field=models.CharField(choices=[('video_play', 'Video play'), ('video_pause', 'Video pause'), ('video_seek', 'Video seek'), ('video_ended', 'Video ended'), ('pdf_open', 'PDF opened'), ('pdf_download', 'PDF downloaded'), ('image_open', 'Image opened'), ('quiz_answer', 'Quiz answer'), ('h5p_answer', 'H5P answer'), ('h5p_attempt', 'H5P attempt finished'), ('h5p_error', 'H5P failed to load')], max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('image', 'Image'), ('pdf', 'PDF'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('h5p', 'H5P activity')], max_length=20),
        ),
        migrations.CreateModel(
            name='H5PPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=8)),
                ('file', models.FileField(upload_to='h5p_uploads/')),
                ('folder', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('main_library', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h5p_packages', to='hub.resource')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['language'],
                'unique_together': {('resource', 'language')},
            },
        ),
    ]
