# Generated by Django 6.0.3 on 2026-10-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0062_h5p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='lesson_type',
            field=models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('image', 'Image'), ('quiz', 'Quiz'), ('pdf', 'PDF'), ('assignment', 'Assignment'), ('h5p', 'H5P activity')], default='text', max_length=20),
        ),
    ]
