from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from .views import (
    AuthoringCourseDetailView,
    AuthoringCoursePublishView,
    AuthoringCoursesView,
    AuthoringLessonDetailView,
    AuthoringLessonReorderView,
    AuthoringLessonView,
    AuthoringModuleDetailView,
    AuthoringModuleEditorView,
    AuthoringModuleReorderView,
    AuthoringModuleView,
    AuthoringPillarsView,
    CourseDetailView,
    CourseEnrollView,
    CourseLearnView,
    CoursesView,
    HomeView,
    LessonCompleteView,
    LessonDetailView,
    LoginView,
    LogoutView,
    MyLearningView,
)

urlpatterns = [
    path('auth/login/', LoginView.as_view(), name='auth-login'),
    path('auth/refresh/', TokenRefreshView.as_view(), name='auth-refresh'),
    path('auth/logout/', LogoutView.as_view(), name='auth-logout'),
    path('courses/', CoursesView.as_view(), name='courses'),
    path('courses/<int:pk>/', CourseDetailView.as_view(), name='course-detail'),
    path('courses/<int:pk>/enroll/', CourseEnrollView.as_view(), name='course-enroll'),
    path('courses/<int:pk>/learn/', CourseLearnView.as_view(), name='course-learn'),
    path('courses/<int:pk>/lessons/<int:lesson_pk>/', LessonDetailView.as_view(), name='lesson-detail'),
    path('courses/<int:pk>/lessons/<int:lesson_pk>/complete/', LessonCompleteView.as_view(), name='lesson-complete'),
    path('home/', HomeView.as_view(), name='home'),
    path('my-learning/', MyLearningView.as_view(), name='my-learning'),
    # Authoring (content_creator only)
    path('authoring/pillars/', AuthoringPillarsView.as_view(), name='authoring-pillars'),
    path('authoring/courses/', AuthoringCoursesView.as_view(), name='authoring-courses'),
    path('authoring/courses/<int:pk>/', AuthoringCourseDetailView.as_view(), name='authoring-course-detail'),
    path('authoring/courses/<int:pk>/modules/', AuthoringModuleView.as_view(), name='authoring-module-create'),
    path('authoring/courses/<int:pk>/modules/reorder/', AuthoringModuleReorderView.as_view(), name='authoring-module-reorder'),
    path('authoring/courses/<int:pk>/modules/<int:module_pk>/', AuthoringModuleDetailView.as_view(), name='authoring-module-detail'),
    path('authoring/courses/<int:pk>/modules/<int:module_pk>/edit/', AuthoringModuleEditorView.as_view(), name='authoring-module-editor'),
    path('authoring/courses/<int:pk>/modules/<int:module_pk>/lessons/', AuthoringLessonView.as_view(), name='authoring-lesson-create'),
    path('authoring/courses/<int:pk>/modules/<int:module_pk>/lessons/reorder/', AuthoringLessonReorderView.as_view(), name='authoring-lesson-reorder'),
    path('authoring/courses/<int:pk>/modules/<int:module_pk>/lessons/<int:lesson_pk>/', AuthoringLessonDetailView.as_view(), name='authoring-lesson-detail'),
    path('authoring/courses/<int:pk>/publish/', AuthoringCoursePublishView.as_view(), name='authoring-course-publish'),
]
