from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from .views import (
    AccessRequestDetailView,
    AccessRequestMineView,
    AccessRequestSeenView,
    AccessRequestView,
    AdminAccessRequestListView,
    AdminAccessRequestReviewView,
    AdminUserListView,
    AdminUserRoleView,
    AuthoringCourseDetailView,
    AuthoringCoursePublishView,
    AuthoringCoursesView,
    AuthoringLessonDetailView,
    AuthoringLessonReorderView,
    AuthoringLessonView,
    AuthoringModuleDetailView,
    AuthoringModuleEditorView,
    AuthoringModuleReorderView,
    AuthoringModuleView,
    AuthoringPillarsView,
    ChangePasswordView,
    CourseDetailView,
    CourseEnrollView,
    CourseLearnView,
    CoursesView,
    HomeView,
    LessonCompleteView,
    LessonDetailView,
    LoginView,
    LogoutView,
    MyLearningView,
    OnboardingView,
    PathwayView,
    ProfilePersonalInfoView,
    ProfilePreferencesView,
    ProfileSettingsView,
    RecommendationEventView,
    RecommendationsView,
    RegisterView,
)

urlpatterns = [
    path('auth/login/', LoginView.as_view(), name='auth-login'),
    path('auth/refresh/', TokenRefreshView.as_view(), name='auth-refresh'),
    path('auth/logout/', LogoutView.as_view(), name='auth-logout'),
    path('auth/register/', RegisterView.as_view(), name='auth-register'),
    path('courses/', CoursesView.as_view(), name='courses'),
    path('courses/<int:pk>/', CourseDetailView.as_view(), name='course-detail'),
    path('courses/<int:pk>/enroll/', CourseEnrollView.as_view(), name='course-enroll'),
    path('courses/<int:pk>/learn/', CourseLearnView.as_view(), name='course-learn'),
    path('courses/<int:pk>/lessons/<int:lesson_pk>/', LessonDetailView.as_view(), name='lesson-detail'),
    path('courses/<int:pk>/lessons/<int:lesson_pk>/complete/', LessonCompleteView.as_view(), name='lesson-complete'),
    path('home/', HomeView.as_view(), name='home'),
    path('my-learning/', MyLearningView.as_view(), name='my-learning'),
    path('onboarding/',           OnboardingView.as_view(),           name='onboarding'),
    path('pathway/',              PathwayView.as_view(),              name='pathway'),
    path('profile/preferences/',  ProfilePreferencesView.as_view(),  name='profile-preferences'),
    path('profile/info/',         ProfilePersonalInfoView.as_view(), name='profile-info'),
    path('profile/settings/',     ProfileSettingsView.as_view(),     name='profile-settings'),
    path('auth/change-password/', ChangePasswordView.as_view(),      name='auth-change-password'),
    path('recommendations/',  RecommendationsView.as_view(),  name='recommendations'),
    path('recommendations/events/', RecommendationEventView.as_view(), name='recommendation-event'),
    # Access requests (user-facing)
    path('access-requests/mine/',         AccessRequestMineView.as_view(),   name='access-request-mine'),
    path('access-requests/',              AccessRequestView.as_view(),       name='access-request'),
    path('access-requests/<int:pk>/',     AccessRequestDetailView.as_view(), name='access-request-detail'),
    path('access-requests/<int:pk>/seen/', AccessRequestSeenView.as_view(), name='access-request-seen'),
    # Admin
    path('admin/users/',                        AdminUserListView.as_view(),           name='admin-users'),
    path('admin/users/<int:pk>/role/',          AdminUserRoleView.as_view(),           name='admin-user-role'),
    path('admin/access-requests/',              AdminAccessRequestListView.as_view(),  name='admin-access-requests'),
    path('admin/access-requests/<int:pk>/',     AdminAccessRequestReviewView.as_view(), name='admin-access-request-review'),
    # Authoring (content_creator only)
    path('authoring/pillars/', AuthoringPillarsView.as_view(), name='authoring-pillars'),
    path('authoring/courses/', AuthoringCoursesView.as_view(), name='authoring-courses'),
    path('authoring/courses/<int:pk>/', AuthoringCourseDetailView.as_view(), name='authoring-course-detail'),
    path('authoring/courses/<int:pk>/modules/', AuthoringModuleView.as_view(), name='authoring-module-create'),
    path('authoring/courses/<int:pk>/modules/reorder/', AuthoringModuleReorderView.as_view(), name='authoring-module-reorder'),
    path('authoring/courses/<int:pk>/modules/<int:module_pk>/', AuthoringModuleDetailView.as_view(), name='authoring-module-detail'),
    path('authoring/courses/<int:pk>/modules/<int:module_pk>/edit/', AuthoringModuleEditorView.as_view(), name='authoring-module-editor'),
    path('authoring/courses/<int:pk>/modules/<int:module_pk>/lessons/', AuthoringLessonView.as_view(), name='authoring-lesson-create'),
    path('authoring/courses/<int:pk>/modules/<int:module_pk>/lessons/reorder/', AuthoringLessonReorderView.as_view(), name='authoring-lesson-reorder'),
    path('authoring/courses/<int:pk>/modules/<int:module_pk>/lessons/<int:lesson_pk>/', AuthoringLessonDetailView.as_view(), name='authoring-lesson-detail'),
    path('authoring/courses/<int:pk>/publish/', AuthoringCoursePublishView.as_view(), name='authoring-course-publish'),
]
