from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from .views import (
    AccessRequestDetailView,
    AccessRequestMineView,
    AccessRequestSeenView,
    AccessRequestView,
    AdminAccessRequestListView,
    AdminAccessRequestReviewView,
    AdminFeedbackDetailView,
    AdminFeedbackListView,
    AdminMaintenanceView,
    AdminRecomputeRecommendationsView,
    AdminSelfEfficacyExportView,
    AdminSelfEfficacyPsychometricsView,
    AdminSelfEfficacyResearchExportView,
    AdminSelfEfficacyView,
    AdminStudyExportView,
    AdminStudyPreregistrationView,
    AdminStudyStatsView,
    AdminStudyView,
    AdminUserListView,
    AdminUserRoleView,
    AssignmentSubmitView,
    AuthoringCourseDetailView,
    AuthoringCourseExportView,
    AuthoringCourseImportView,
    AuthoringCoursePublishView,
    AuthoringCoursesView,
    AuthoringCourseTemplateView,
    AuthoringCourseTranslateView,
    AuthoringCourseUnpublishView,
    AuthoringLessonDetailView,
    AuthoringLessonReorderView,
    AuthoringLessonView,
    AuthoringModuleDetailView,
    AuthoringModuleEditorView,
    AuthoringModuleReorderView,
    AuthoringModuleView,
    AuthoringPillarsView,
    AuthoringTranslationReviewView,
    AuthoringUploadView,
    ChangePasswordView,
    ConversationDetailView,
    ConversationListView,
    CourseDetailView,
    CourseEnrollView,
    CourseLearnView,
    CoursesView,
    FeedbackMineView,
    FeedbackUploadView,
    FeedbackView,
    HomeView,
    LessonCompleteView,
    LessonDetailView,
    LoginView,
    LogoutView,
    MaintenanceView,
    MeView,
    MyLearningView,
    OnboardingView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    PathwayView,
    PreferenceQuizView,
    ProfileAvatarView,
    ProfileLanguageView,
    ProfilePersonalInfoView,
    ProfilePreferencesView,
    ProfileSettingsView,
    PublicProfileView,
    QuizCheckView,
    RecommendationEventView,
    RecommendationsView,
    RegisterView,
    ResendVerificationView,
    ReviewActionView,
    ReviewQueueView,
    SelfEfficacyRetakeView,
    SelfEfficacyView,
    StudyAssessmentView,
    StudyConsentView,
    StudyStatusView,
    SubjectsView,
    SubmissionUploadView,
    UnreadMessageCountView,
    VerifyEmailView,
)

urlpatterns = [
    path('auth/login/', LoginView.as_view(), name='auth-login'),
    path('auth/refresh/', TokenRefreshView.as_view(), name='auth-refresh'),
    path('auth/logout/', LogoutView.as_view(), name='auth-logout'),
    path('auth/me/', MeView.as_view(), name='auth-me'),
    path('auth/register/', RegisterView.as_view(), name='auth-register'),
    path('auth/verify-email/', VerifyEmailView.as_view(), name='auth-verify-email'),
    path('auth/verify-email/resend/', ResendVerificationView.as_view(), name='auth-verify-email-resend'),
    path('auth/password-reset/', PasswordResetRequestView.as_view(), name='auth-password-reset'),
    path('auth/password-reset/confirm/', PasswordResetConfirmView.as_view(), name='auth-password-reset-confirm'),
    path('courses/', CoursesView.as_view(), name='courses'),
    path('courses/<int:pk>/', CourseDetailView.as_view(), name='course-detail'),
    path('courses/<int:pk>/enroll/', CourseEnrollView.as_view(), name='course-enroll'),
    path('courses/<int:pk>/learn/', CourseLearnView.as_view(), name='course-learn'),
    path('courses/<int:pk>/lessons/<int:lesson_pk>/', LessonDetailView.as_view(), name='lesson-detail'),
    path('courses/<int:pk>/lessons/<int:lesson_pk>/complete/', LessonCompleteView.as_view(), name='lesson-complete'),
    path('courses/<int:pk>/lessons/<int:lesson_pk>/quiz-check/', QuizCheckView.as_view(), name='quiz-check'),
    path('courses/<int:pk>/lessons/<int:lesson_pk>/submit-assignment/', AssignmentSubmitView.as_view(), name='assignment-submit'),
    path('courses/<int:pk>/lessons/<int:lesson_pk>/submission-upload/', SubmissionUploadView.as_view(), name='submission-upload'),
    path('reviews/', ReviewQueueView.as_view(), name='review-queue'),
    path('reviews/<int:pk>/', ReviewActionView.as_view(), name='review-action'),
    path('home/', HomeView.as_view(), name='home'),
    path('my-learning/', MyLearningView.as_view(), name='my-learning'),
    path('onboarding/',           OnboardingView.as_view(),           name='onboarding'),
    path('self-efficacy/',        SelfEfficacyView.as_view(),         name='self-efficacy'),
    path('self-efficacy/retake/', SelfEfficacyRetakeView.as_view(),   name='self-efficacy-retake'),
    path('pathway/',              PathwayView.as_view(),              name='pathway'),
    path('preference-quiz/',      PreferenceQuizView.as_view(),      name='preference-quiz'),
    path('subjects/',             SubjectsView.as_view(),             name='subjects'),
    path('maintenance/',          MaintenanceView.as_view(),          name='maintenance'),
    path('users/<int:pk>/profile/', PublicProfileView.as_view(),       name='public-profile'),
    # Messaging
    path('messages/conversations/', ConversationListView.as_view(),    name='conversation-list'),
    path('messages/unread-count/',  UnreadMessageCountView.as_view(),  name='message-unread-count'),
    path('messages/with/<int:user_id>/', ConversationDetailView.as_view(), name='conversation-detail'),
    # Study (adaptive-vs-fixed comparison)
    path('study/status/',     StudyStatusView.as_view(),     name='study-status'),
    path('study/consent/',    StudyConsentView.as_view(),    name='study-consent'),
    path('study/assessment/', StudyAssessmentView.as_view(), name='study-assessment'),
    # Feedback
    path('feedback/',        FeedbackView.as_view(),       name='feedback'),
    path('feedback/mine/',   FeedbackMineView.as_view(),   name='feedback-mine'),
    path('feedback/upload/', FeedbackUploadView.as_view(), name='feedback-upload'),
    path('profile/preferences/',  ProfilePreferencesView.as_view(),  name='profile-preferences'),
    path('profile/info/',         ProfilePersonalInfoView.as_view(), name='profile-info'),
    path('profile/settings/',     ProfileSettingsView.as_view(),     name='profile-settings'),
    path('auth/change-password/', ChangePasswordView.as_view(),      name='auth-change-password'),
    path('profile/avatar/',       ProfileAvatarView.as_view(),       name='profile-avatar'),
    path('profile/language/',     ProfileLanguageView.as_view(),     name='profile-language'),
    path('recommendations/',  RecommendationsView.as_view(),  name='recommendations'),
    path('recommendations/events/', RecommendationEventView.as_view(), name='recommendation-event'),
    # Access requests (user-facing)
    path('access-requests/mine/',         AccessRequestMineView.as_view(),   name='access-request-mine'),
    path('access-requests/',              AccessRequestView.as_view(),       name='access-request'),
    path('access-requests/<int:pk>/',     AccessRequestDetailView.as_view(), name='access-request-detail'),
    path('access-requests/<int:pk>/seen/', AccessRequestSeenView.as_view(), name='access-request-seen'),
    # Admin
    path('admin/users/',                        AdminUserListView.as_view(),           name='admin-users'),
    path('admin/users/<int:pk>/role/',          AdminUserRoleView.as_view(),           name='admin-user-role'),
    path('admin/recompute-recommendations/',    AdminRecomputeRecommendationsView.as_view(), name='admin-recompute-recommendations'),
    path('admin/access-requests/',              AdminAccessRequestListView.as_view(),  name='admin-access-requests'),
    path('admin/access-requests/<int:pk>/',     AdminAccessRequestReviewView.as_view(), name='admin-access-request-review'),
    path('admin/feedback/',                     AdminFeedbackListView.as_view(),   name='admin-feedback'),
    path('admin/feedback/<int:pk>/',            AdminFeedbackDetailView.as_view(), name='admin-feedback-detail'),
    path('admin/study/',                        AdminStudyView.as_view(),          name='admin-study'),
    path('admin/study/export/',                 AdminStudyExportView.as_view(),    name='admin-study-export'),
    path('admin/study/stats/',                  AdminStudyStatsView.as_view(),    name='admin-study-stats'),
    path('admin/study/preregister/',            AdminStudyPreregistrationView.as_view(), name='admin-study-preregister'),
    path('admin/maintenance/',                  AdminMaintenanceView.as_view(),          name='admin-maintenance'),
    path('admin/self-efficacy/',                AdminSelfEfficacyView.as_view(),         name='admin-self-efficacy'),
    path('admin/self-efficacy/export/',         AdminSelfEfficacyExportView.as_view(),   name='admin-self-efficacy-export'),
    path('admin/self-efficacy/psychometrics/',  AdminSelfEfficacyPsychometricsView.as_view(), name='admin-self-efficacy-psychometrics'),
    path('admin/self-efficacy/research-export/', AdminSelfEfficacyResearchExportView.as_view(), name='admin-self-efficacy-research-export'),
    # Authoring (content_creator only)
    path('authoring/pillars/', AuthoringPillarsView.as_view(), name='authoring-pillars'),
    path('authoring/upload/', AuthoringUploadView.as_view(), name='authoring-upload'),
    path('authoring/courses/', AuthoringCoursesView.as_view(), name='authoring-courses'),
    path('authoring/courses/import/', AuthoringCourseImportView.as_view(), name='authoring-course-import'),
    path('authoring/courses/template/', AuthoringCourseTemplateView.as_view(), name='authoring-course-template'),
    path('authoring/courses/<int:pk>/', AuthoringCourseDetailView.as_view(), name='authoring-course-detail'),
    path('authoring/courses/<int:pk>/export/', AuthoringCourseExportView.as_view(), name='authoring-course-export'),
    path('authoring/courses/<int:pk>/modules/', AuthoringModuleView.as_view(), name='authoring-module-create'),
    path('authoring/courses/<int:pk>/modules/reorder/', AuthoringModuleReorderView.as_view(), name='authoring-module-reorder'),
    path('authoring/courses/<int:pk>/modules/<int:module_pk>/', AuthoringModuleDetailView.as_view(), name='authoring-module-detail'),
    path('authoring/courses/<int:pk>/modules/<int:module_pk>/edit/', AuthoringModuleEditorView.as_view(), name='authoring-module-editor'),
    path('authoring/courses/<int:pk>/modules/<int:module_pk>/lessons/', AuthoringLessonView.as_view(), name='authoring-lesson-create'),
    path('authoring/courses/<int:pk>/modules/<int:module_pk>/lessons/reorder/', AuthoringLessonReorderView.as_view(), name='authoring-lesson-reorder'),
    path('authoring/courses/<int:pk>/modules/<int:module_pk>/lessons/<int:lesson_pk>/', AuthoringLessonDetailView.as_view(), name='authoring-lesson-detail'),
    path('authoring/courses/<int:pk>/publish/', AuthoringCoursePublishView.as_view(), name='authoring-course-publish'),
    path('authoring/courses/<int:pk>/unpublish/', AuthoringCourseUnpublishView.as_view(), name='authoring-course-unpublish'),
    path('authoring/courses/<int:pk>/translate/', AuthoringCourseTranslateView.as_view(), name='authoring-course-translate'),
    path('authoring/courses/<int:pk>/translation-review/', AuthoringTranslationReviewView.as_view(), name='authoring-translation-review'),
]
